export const foodInfo = [
  {
    name: "Carne New York",
    ingredients: "New york and others",
    category: "Steaks",
    price: 550,
    image: "/images/Food/striploin.jpg",
    image_alt: "imagen carnde new york",
  },
  {
    name: "Rib eye",
    ingredients: "Carne rib eye, salsa",
    category: "Steaks",
    price: 600,
    image: "/images/Food/ribeye.jpg",
    image_alt: "imagen carne ribeye",
  },
  {
    name: "Pulpa negra",
    ingredients: "carne pulpa negra, aguacate",
    category: "Steaks",
    price: 550,
    image: "/images/Food/pulpanegra.jpg",
    image_alt: "imagen carne pulpa negra",
  },
  {
    name: "Pozole",
    ingredients: "Elote, agua",
    category: "Entries",
    price: 120,
    image: "/images/Food/pozole_rojo.jpg",
    image_alt: "imagen pozole rojo",
  },
  {
    name: "Mole",
    ingredients: "Pollo, salsa chocolate",
    category: "Entries",
    price: 120,
    image: "/images/Food/mole_poblano.jpg",
    image_alt: "imagen mole",
  },
  {
    name: "Chiles en nogada",
    ingredients: "Chile, queso, salsa",
    category: "Entries",
    price: 150,
    image: "/images/Food/chiles_nogada.jpg",
    image_alt: "imagen chile en nogada",
  },
  {
    name: "Enchiladas",
    ingredients: "Tortillas, salsa, pollo",
    category: "Entries",
    price: 90,
    image: "/images/Food/enchiladas_verdes.jpg",
    image_alt: "imagen enchiladas verdes",
  },
  {
    name: "Tacos de adobada",
    ingredients: "carne, tortilla, aguacate",
    category: "Entries",
    price: 60,
    image: "/images/Food/tacos.jpg",
    image_alt: "imagen tacos",
  },
  {
    name: "Huevos rancheros",
    ingredients: "huevo, tomate",
    category: "Entries",
    price: 70,
    image: "/images/Food/huevos_rancheros.jpg",
    image_alt: "imagen huevos rancheros",
  },
  /* Postres */
  {
    name: "Flan",
    ingredients: "No se",
    category: "Dessert",
    price: 70,
    image: "/images/Dessert/flan.jpg",
    image_alt: "imagen huevos rancheros",
  },
  {
    name: "Pay de queso",
    ingredients: "huevo, queso, leche o no se",
    category: "Dessert",
    price: 70,
    image: "/images/Dessert/pay_queso.jpg",
    image_alt: "imagen huevos rancheros",
  },
  {
    name: "Pastel de chocolate",
    ingredients: "chocolate y algo mas",
    category: "Dessert",
    price: 70,
    image: "/images/Dessert/pastel_chocolate.jpg",
    image_alt: "imagen huevos rancheros",
  },
  {
    name: "Pastel de elote",
    ingredients: "elote, no se carnal",
    category: "Dessert",
    price: 70,
    image: "/images/Dessert/pan_elote.jpg",
    image_alt: "imagen huevos rancheros",
  },
];

export const drinkInfo = [
  {
    name: "Agua Mineral",
    category: "Drinks",
    price: 25,
    image: "/images/Drinks/agua_mineral.jpg",
    image_alt: "imagen agua mineral",
  },
  {
    name: "Limonada",
    category: "Drinks",
    price: 50,
    image: "/images/Drinks/limonada.jpg",
    image_alt: "imagen limonada",
  },
  {
    name: "Naranjada",
    category: "Drinks",
    price: 60,
    image: "/images/Drinks/naranjada.jpg",
    image_alt: "imagen naranjada",
  },
  {
    name: "Cerveza",
    category: "Drinks",
    price: 50,
    image: "/images/Drinks/modelo_beer.jpg",
    image_alt: "imagen cerveza",
  },
];

export const Category = [
  {
    title: "Entradas",
    image: "/Entries.jpg",
    image_alt: "Imagen Comida Entradas",
    category: "Appetizers",
  },
  {
    title: "Carnes",
    image: "/Steak.jpg",
    image_alt: "Imagen Carne",
    category: "Steaks",
  },
  {
    title: "Postres",
    image: "dessert.jpg",
    image_alt: "Imagen Postre",
    category: "Dessert",
  },
  {
    title: "Bebidas",
    image: "drinks.jpg",
    image_alt: "Imagen Bebidas",
    category: "Drinks",
  },
];
